// quizData.js

const quizQuestions = [
    {
        "date": "2025-06-16",
        "question": "Quel événement célèbre la vie et l'œuvre de James Joyce le 16 juin ?",
        "correctAnswer": "Bloomsday",
        "options": ["Joyce Day", "Dublin Festival", "Bloomsday"]
    },
    {
        "date": "2025-06-17",
        "question": "Quelle célèbre statue est arrivée à New York le 17 juin 1885 ?",
        "correctAnswer": "La Statue de la Liberté",
        "options": ["La Statue de la Liberté", "Le Christ Rédempteur", "La Vénus de Milo"]
    },
    {
        "date": "2025-06-18",
        "question": "Qui a été définitivement vaincu à la bataille de Waterloo le 18 juin 1815 ?",
        "correctAnswer": "Napoléon Bonaparte",
        "options": ["George Washington", "Napoléon Bonaparte", "Jules César"]
    },
    {
        "date": "2025-06-19",
        "question": "Quel événement de libération des esclaves est célébré le 19 juin aux États-Unis ?",
        "correctAnswer": "Juneteenth",
        "options": ["Emancipation Day", "Freedom Day", "Juneteenth"]
    },
    {
        "date": "2025-06-20",
        "question": "Quelle journée mondiale est célébrée le 20 juin ?",
        "correctAnswer": "Journée Mondiale des Réfugiés",
        "options": ["Journée de la Paix", "Journée Mondiale des Réfugiés", "Journée de l'Environnement"]
    },
    {
        "date": "2025-06-21",
        "question": "Outre le solstice d'été, quelle fête musicale est célébrée le 21 juin ?",
        "correctAnswer": "Fête de la Musique",
        "options": ["Fête du Solstice", "Fête de la Danse", "Fête de la Musique"]
    },
    {
        "date": "2025-06-22",
        "question": "Quelle opération militaire majeure a commencé le 22 juin 1941, avec l'invasion de l'URSS ?",
        "correctAnswer": "Opération Barbarossa",
        "options": ["Opération Overlord", "Opération Barbarossa", "Opération Desert Storm"]
    },
    {
        "date": "2025-06-23",
        "question": "Quelle organisation internationale a été fondée à Paris le 23 juin 1894 ?",
        "correctAnswer": "Comité International Olympique",
        "options": ["Nations Unies", "Comité International Olympique", "Croix-Rouge"]
    },
    {
        "date": "2025-06-24",
        "question": "Quelle fête nationale est célébrée au Québec le 24 juin ?",
        "correctAnswer": "Saint-Jean-Baptiste",
        "options": ["Canada Day", "Saint-Jean-Baptiste", "Journée des Patriotes"]
    },
    {
        "date": "2025-06-25",
        "question": "Quel conflit a débuté le 25 juin 1950, durant la Guerre Froide ?",
        "correctAnswer": "La Guerre de Corée",
        "options": ["La Guerre du Vietnam", "La Guerre de Corée", "La Guerre du Golfe"]
    },
    {
        "date": "2025-06-26",
        "question": "Quelle charte importante a été signée le 26 juin 1945, créant l'ONU ?",
        "correctAnswer": "Charte des Nations Unies",
        "options": ["Charte de l'Atlantique", "Charte des Nations Unies", "Déclaration universelle des droits de l'homme"]
    },
    {
        "date": "2025-06-27",
        "question": "Quel brevet a été accordé le 27 juin 1893 à Whitcomb L. Judson ?",
        "correctAnswer": "La fermeture éclair",
        "options": ["L'ampoule électrique", "La fermeture éclair", "Le téléphone"]
    },
    {
        "date": "2025-06-28",
        "question": "Quel événement tragique a déclenché la Première Guerre mondiale le 28 juin 1914 ?",
        "correctAnswer": "L'assassinat de l'Archiduc François-Ferdinand",
        "options": ["La déclaration de guerre de l'Allemagne", "L'assassinat de l'Archiduc François-Ferdinand", "Le bombardement de Pearl Harbor"]
    },
    {
        "date": "2025-06-29",
        "question": "Quel produit révolutionnaire a été commercialisé pour la première fois le 29 juin 2007 ?",
        "correctAnswer": "Le premier iPhone",
        "options": ["Le premier iPad", "Le premier iPhone", "Le premier iPod"]
    },
    {
        "date": "2025-06-30",
        "question": "Quelle explosion massive d'origine inconnue a dévasté une région de Sibérie le 30 juin 1908 ?",
        "correctAnswer": "L'événement de la Toungouska",
        "options": ["L'explosion de Tchernobyl", "L'événement de la Toungouska", "L'éruption du Mont Saint Helens"]
    },

    {
        "date": "2025-07-01",
        "question": "Quelle fête nationale est célébrée au Canada le 1er juillet ?",
        "correctAnswer": "Fête du Canada",
        "options": ["Thanksgiving", "Fête de la Reine", "Fête du Canada"]
    },
    {
        "date": "2025-07-02",
        "question": "Quel supermarché a ouvert ses portes pour la première fois le 2 juillet 1962 ?",
        "correctAnswer": "Walmart",
        "options": ["Target", "Kroger", "Walmart"]
    },
    {
        "date": "2025-07-03",
        "question": "Quel pays a proclamé son indépendance de la France le 3 juillet 1962 ?",
        "correctAnswer": "L'Algérie",
        "options": ["Le Maroc", "La Tunisie", "L'Algérie"]
    },
    {
        "date": "2025-07-04",
        "question": "Quel jour est l'Independence Day aux États-Unis ?",
        "correctAnswer": "Le 4 juillet",
        "options": ["Le 14 juillet", "Le 4 juillet", "Le 17 septembre"]
    },
    {
        "date": "2025-07-05",
        "question": "Quel maillot de bain jugé scandaleux a été présenté à Paris le 5 juillet 1946 ?",
        "correctAnswer": "Le bikini",
        "options": ["Le monokini", "Le bikini", "Le trikini"]
    },
    {
        "date": "2025-07-06",
        "question": "Quels célèbres musiciens se sont rencontrés pour la première fois le 6 juillet 1957 ?",
        "correctAnswer": "John Lennon et Paul McCartney",
        "options": ["Mick Jagger et Keith Richards", "Elvis Presley et Johnny Cash", "John Lennon et Paul McCartney"]
    },
    {
        "date": "2025-07-07",
        "question": "Quelles nouvelles merveilles ont été annoncées le 7 juillet 2007, suite à un vote mondial ?",
        "correctAnswer": "Les Nouvelles Sept Merveilles du Monde",
        "options": ["Les Sept Merveilles du Monde Antique", "Les Sept Merveilles de l'Ingénierie", "Les Nouvelles Sept Merveilles du Monde"]
    },
    {
        "date": "2025-07-08",
        "question": "Quel célèbre journal financier a été publié pour la première fois le 8 juillet 1889 ?",
        "correctAnswer": "Le Wall Street Journal",
        "options": ["Le New York Times", "Le Financial Times", "Le Wall Street Journal"]
    },
    {
        "date": "2025-07-09",
        "question": "Quel pays a déclaré son indépendance de l'Espagne le 9 juillet 1816 ?",
        "correctAnswer": "L'Argentine",
        "options": ["Le Chili", "Le Pérou", "L'Argentine"]
    },
    {
        "date": "2025-07-10",
        "question": "Quel navire de Greenpeace a été coulé par les services secrets français le 10 juillet 1985 ?",
        "correctAnswer": "Le Rainbow Warrior",
        "options": ["Le Sea Shepherd", "Le Greenpeace II", "Le Rainbow Warrior"]
    },
    {
        "date": "2025-07-11",
        "question": "Quel jour, en 1987, la population mondiale a-t-elle atteint 5 milliards d'habitants ?",
        "correctAnswer": "Jour des Cinq Milliards",
        "options": ["Jour de la Population", "Jour des Cinq Milliards", "Jour de la Croissance Démographique"]
    },
    {
        "date": "2025-07-12",
        "question": "Quelle équipe nationale de football a remporté la Coupe du Monde à domicile le 12 juillet 1998 ?",
        "correctAnswer": "L'équipe de France",
        "options": ["L'équipe du Brésil", "L'équipe d'Allemagne", "L'équipe de France"]
    },
    {
        "date": "2025-07-13",
        "question": "Quelle compétition sportive majeure a été lancée le 13 juillet 1930 en Uruguay ?",
        "correctAnswer": "La première Coupe du Monde de football",
        "options": ["Les Jeux Olympiques modernes", "La première Coupe du Monde de football", "Le Tour de France cycliste"]
    },
    {
        "date": "2025-07-14",
        "question": "Quel événement commémore la Fête Nationale française le 14 juillet ?",
        "correctAnswer": "La prise de la Bastille",
        "options": ["La Révolution Française", "La prise de la Bastille", "La proclamation de la République"]
    },
    {
        "date": "2025-07-15",
        "question": "Quelle ville a été prise par les croisés le 15 juillet 1099, lors de la Première Croisade ?",
        "correctAnswer": "Jérusalem",
        "options": ["Rome", "Constantinople", "Jérusalem"]
    },
    {
        "date": "2025-07-16",
        "question": "Quelle mission spatiale emblématique a décollé le 16 juillet 1969, en route vers la Lune ?",
        "correctAnswer": "Apollo 11",
        "options": ["Soyouz 1", "Gemini 8", "Apollo 11"]
    },
    {
        "date": "2025-07-17",
        "question": "Quelle conférence alliée a débuté le 17 juillet 1945 pour discuter de l'après-guerre ?",
        "correctAnswer": "La Conférence de Potsdam",
        "options": ["La Conférence de Yalta", "La Conférence de Téhéran", "La Conférence de Potsdam"]
    },
    {
        "date": "2025-07-18",
        "question": "Quel leader sud-africain, né le 18 juillet 1918, a donné son nom au Mandela Day ?",
        "correctAnswer": "Nelson Mandela",
        "options": ["Desmond Tutu", "Nelson Mandela", "Oliver Tambo"]
    },
    {
        "date": "2025-07-19",
        "question": "Où a eu lieu la première convention pour les droits des femmes aux États-Unis le 19 juillet 1848 ?",
        "correctAnswer": "Seneca Falls",
        "options": ["New York City", "Washington D.C.", "Seneca Falls"]
    },
    {
        "date": "2025-07-20",
        "question": "Qui est devenu le premier homme à marcher sur la Lune le 20 juillet 1969 ?",
        "correctAnswer": "Neil Armstrong",
        "options": ["Buzz Aldrin", "Neil Armstrong", "Michael Collins"]
    },
    {
        "date": "2025-07-21",
        "question": "Quel conte célèbre a été publié pour la première fois le 21 juillet 1845 par Hans Christian Andersen ?",
        "correctAnswer": "La Reine des Neiges",
        "options": ["La Petite Sirène", "Le Vilain Petit Canard", "La Reine des Neiges"]
    },
    {
        "date": "2025-07-22",
        "question": "Quel pilote a achevé le premier vol solo autour du monde le 22 juillet 1933 ?",
        "correctAnswer": "Wiley Post",
        "options": ["Charles Lindbergh", "Amelia Earhart", "Wiley Post"]
    },
    {
        "date": "2025-07-23",
        "question": "Quel brevet important a été publié le 23 juillet 1829 par William Burt ?",
        "correctAnswer": "La machine à écrire",
        "options": ["La locomotive à vapeur", "Le télégraphe", "La machine à écrire"]
    },
    {
        "date": "2025-07-24",
        "question": "Quelle mission spatiale a amerrit avec succès le 24 juillet 1969, ramenant les astronautes de la Lune ?",
        "correctAnswer": "Apollo 11",
        "options": ["Apollo 8", "Apollo 13", "Apollo 11"]
    },
    {
        "date": "2025-07-25",
        "question": "Quel événement marquant dans l'histoire de la médecine a eu lieu le 25 juillet 1978 ?",
        "correctAnswer": "Naissance du premier 'bébé-éprouvette'",
        "options": ["Première transplantation cardiaque", "Découverte de la pénicilline", "Naissance du premier 'bébé-éprouvette'"]
    },
    {
        "date": "2025-07-26",
        "question": "Quel leader a mené l'attaque sur la caserne de Moncada le 26 juillet 1953, début de la Révolution cubaine ?",
        "correctAnswer": "Fidel Castro",
        "options": ["Che Guevara", "Fidel Castro", "Raúl Castro"]
    },
    {
        "date": "2025-07-27",
        "question": "Quel armistice a été signé le 27 juillet 1953, mettant fin aux combats de la Guerre de Corée ?",
        "correctAnswer": "L'armistice de Panmunjeom",
        "options": ["L'armistice de Versailles", "L'armistice de Panmunjeom", "L'armistice de Compiègne"]
    },
    {
        "date": "2025-07-28",
        "question": "Quelle déclaration de guerre, le 28 juillet 1914, a marqué le début officiel de la Première Guerre mondiale ?",
        "correctAnswer": "Autriche-Hongrie à la Serbie",
        "options": ["Allemagne à la France", "Autriche-Hongrie à la Serbie", "Royaume-Uni à l'Allemagne"]
    },
    {
        "date": "2025-07-29",
        "question": "Quel mariage royal célèbre a eu lieu le 29 juillet 1981 à Londres ?",
        "correctAnswer": "Prince Charles et Lady Diana",
        "options": ["Prince William et Kate Middleton", "Prince Harry et Meghan Markle", "Prince Charles et Lady Diana"]
    },
    {
        "date": "2025-07-30",
        "question": "Quel pays a remporté la première Coupe du Monde de football le 30 juillet 1930 ?",
        "correctAnswer": "L'Uruguay",
        "options": ["Le Brésil", "L'Argentine", "L'Uruguay"]
    },
    {
        "date": "2025-07-31",
        "question": "Quelle mission spatiale est retournée sur Terre le 31 juillet 1969 après son voyage historique sur la Lune ?",
        "correctAnswer": "Apollo 11",
        "options": ["Apollo 10", "Apollo 11", "Apollo 12"]
    },

    {
        "date": "2025-08-01",
        "question": "Quel pays a déclaré la guerre à la Russie le 1er août 1914, marquant une escalade de la Première Guerre mondiale ?",
        "correctAnswer": "L'Allemagne",
        "options": ["La France", "L'Autriche-Hongrie", "L'Allemagne"]
    },
    {
        "date": "2025-08-02",
        "question": "Qui est devenu Führer et chancelier de l'Allemagne le 2 août 1934 ?",
        "correctAnswer": "Adolf Hitler",
        "options": ["Benito Mussolini", "Adolf Hitler", "Joseph Staline"]
    },
    {
        "date": "2025-08-03",
        "question": "Quel explorateur a quitté l'Espagne le 3 août 1492 pour son premier voyage vers les Amériques ?",
        "correctAnswer": "Christophe Colomb",
        "options": ["Vasco de Gama", "Fernand de Magellan", "Christophe Colomb"]
    },
    {
        "date": "2025-08-04",
        "question": "Quel pays a déclaré la guerre à l'Allemagne le 4 août 1914, s'engageant dans la Première Guerre mondiale ?",
        "correctAnswer": "Le Royaume-Uni",
        "options": ["Les États-Unis", "Le Royaume-Uni", "L'Italie"]
    },
    {
        "date": "2025-08-05",
        "question": "Quelle icône hollywoodienne est décédée le 5 août 1962 ?",
        "correctAnswer": "Marilyn Monroe",
        "options": ["Audrey Hepburn", "Grace Kelly", "Marilyn Monroe"]
    },
    {
        "date": "2025-08-06",
        "question": "Quelle ville japonaise a subi le largage de la première bombe atomique le 6 août 1945 ?",
        "correctAnswer": "Hiroshima",
        "options": ["Nagasaki", "Tokyo", "Hiroshima"]
    },
    {
        "date": "2025-08-07",
        "question": "Quels événements ont eu lieu le 7 août 1998, tuant plus de 200 personnes dans des ambassades américaines ?",
        "correctAnswer": "Attentats à la bombe en Tanzanie et au Kenya",
        "options": ["Attentats du 11 Septembre", "Attentats à la bombe en Tanzanie et au Kenya", "Attentats de Londres"]
    },
    {
        "date": "2025-08-08",
        "question": "Quel président américain a annoncé sa démission le 8 août 1974 suite au scandale du Watergate ?",
        "correctAnswer": "Richard Nixon",
        "options": ["John F. Kennedy", "Lyndon B. Johnson", "Richard Nixon"]
    },
    {
        "date": "2025-08-09",
        "question": "Quelle ville japonaise a subi le largage de la deuxième bombe atomique le 9 août 1945 ?",
        "correctAnswer": "Nagasaki",
        "options": ["Hiroshima", "Nagasaki", "Kyoto"]
    },
    {
        "date": "2025-08-10",
        "question": "Quelle insurrection, le 10 août 1792, a mené à la chute de la monarchie française ?",
        "correctAnswer": "L'insurrection de la Commune de Paris",
        "options": ["La prise de la Bastille", "L'insurrection de la Commune de Paris", "Le coup d'État du 18 Brumaire"]
    },
    {
        "date": "2025-08-11",
        "question": "Quelle légende du baseball a frappé son 500e home run le 11 août 1929 ?",
        "correctAnswer": "Babe Ruth",
        "options": ["Jackie Robinson", "Babe Ruth", "Lou Gehrig"]
    },
    {
        "date": "2025-08-12",
        "question": "Quel géant de l'informatique a lancé son premier ordinateur personnel (PC) le 12 août 1981 ?",
        "correctAnswer": "IBM",
        "options": ["Apple", "Microsoft", "IBM"]
    },
    {
        "date": "2025-08-13",
        "question": "Quelle construction a commencé le 13 août 1961, divisant Berlin en Est et Ouest ?",
        "correctAnswer": "Le mur de Berlin",
        "options": ["La Porte de Brandebourg", "Le Reichstag", "Le mur de Berlin"]
    },
    {
        "date": "2025-08-14",
        "question": "Quel pays a capitulé le 14 août 1945, mettant fin à la Seconde Guerre mondiale ?",
        "correctAnswer": "Le Japon",
        "options": ["L'Allemagne", "L'Italie", "Le Japon"]
    },
    {
        "date": "2025-08-15",
        "question": "Quelle fête religieuse importante est célébrée le 15 août en France ?",
        "correctAnswer": "L'Assomption",
        "options": ["La Toussaint", "Noël", "L'Assomption"]
    },
    {
        "date": "2025-08-16",
        "question": "Quel 'Roi du Rock and Roll' est décédé le 16 août 1977 ?",
        "correctAnswer": "Elvis Presley",
        "options": ["Johnny Cash", "Chuck Berry", "Elvis Presley"]
    },
    {
        "date": "2025-08-17",
        "question": "Quel support audio a été produit pour la première fois en Allemagne le 17 août 1982 ?",
        "correctAnswer": "Le premier CD audio",
        "options": ["Le premier vinyle", "Le premier CD audio", "La première cassette audio"]
    },
    {
        "date": "2025-08-18",
        "question": "Quel amendement de la Constitution américaine, ratifié le 18 août 1920, a donné le droit de vote aux femmes ?",
        "correctAnswer": "Le 19e amendement",
        "options": ["Le 13e amendement", "Le 19e amendement", "Le 26e amendement"]
    },
    {
        "date": "2025-08-19",
        "question": "Quel engin a réalisé son premier vol le 19 août 1909 en Allemagne ?",
        "correctAnswer": "Le dirigeable Zeppelin",
        "options": ["L'avion des frères Wright", "Le dirigeable Zeppelin", "La fusée V-2"]
    },
    {
        "date": "2025-08-20",
        "question": "Quel événement, le 20 août 1968, a vu l'Union Soviétique envahir la Tchécoslovaquie ?",
        "correctAnswer": "Le Printemps de Prague",
        "options": ["La Révolution de Velours", "Le Printemps de Prague", "La Dissolution du Pacte de Varsovie"]
    },
    {
        "date": "2025-08-21",
        "question": "Quelle célèbre œuvre d'art a été volée du Louvre le 21 août 1911 ?",
        "correctAnswer": "La Joconde",
        "options": ["La Vénus de Milo", "La Joconde", "Le Radeau de la Méduse"]
    },
    {
        "date": "2025-08-22",
        "question": "Quelle bataille, le 22 août 1485, a marqué la fin de la Guerre des Deux-Roses en Angleterre ?",
        "correctAnswer": "La Bataille de Bosworth Field",
        "options": ["La Bataille d'Azincourt", "La Bataille de Hastings", "La Bataille de Bosworth Field"]
    },
    {
        "date": "2025-08-23",
        "question": "Quelle journée internationale est célébrée le 23 août en lien avec la traite négrière ?",
        "correctAnswer": "Journée internationale du souvenir de la traite négrière et de son abolition",
        "options": ["Journée de la liberté", "Journée internationale des droits de l'homme", "Journée internationale du souvenir de la traite négrière et de son abolition"]
    },
    {
        "date": "2025-08-24",
        "question": "Quelle éruption volcanique, le 24 août 79 après J.-C., a enseveli Pompéi et Herculanum ?",
        "correctAnswer": "L'éruption du Vésuve",
        "options": ["L'éruption du Krakatoa", "L'éruption du Vésuve", "L'éruption du Mont Saint Helens"]
    },
    {
        "date": "2025-08-25",
        "question": "Quelle ville a été libérée de l'occupation allemande le 25 août 1944 pendant la Seconde Guerre mondiale ?",
        "correctAnswer": "Paris",
        "options": ["Londres", "Berlin", "Paris"]
    },
    {
        "date": "2025-08-26",
        "question": "Quelle déclaration fondamentale a été adoptée en France le 26 août 1789 ?",
        "correctAnswer": "La Déclaration des Droits de l'Homme et du Citoyen",
        "options": ["La Magna Carta", "La Déclaration d'Indépendance des États-Unis", "La Déclaration des Droits de l'Homme et du Citoyen"]
    },
    {
        "date": "2025-08-27",
        "question": "Quelle éruption volcanique majeure, le 27 août 1883, a provoqué un raz-de-marée dévastateur ?",
        "correctAnswer": "L'éruption du Krakatoa",
        "options": ["L'éruption du Mont Fuji", "L'éruption du Krakatoa", "L'éruption du Stromboli"]
    },
    {
        "date": "2025-08-28",
        "question": "Quel célèbre discours 'I Have a Dream' a été prononcé le 28 août 1963 par Martin Luther King Jr. ?",
        "correctAnswer": "À Washington D.C.",
        "options": ["À New York City", "À Washington D.C.", "À Atlanta"]
    },
    {
        "date": "2025-08-29",
        "question": "Quelle entreprise de streaming, fondée le 29 août 1997, a révolutionné le divertissement ?",
        "correctAnswer": "Netflix",
        "options": ["Blockbuster", "Hulu", "Netflix"]
    },
    {
        "date": "2025-08-30",
        "question": "Quel pays a déclaré son indépendance de l'Union Soviétique le 30 août 1991 ?",
        "correctAnswer": "L'Azerbaïdjan",
        "options": ["L'Ukraine", "La Lituanie", "L'Azerbaïdjan"]
    },
    {
        "date": "2025-08-31",
        "question": "Qui est décédée tragiquement le 31 août 1997 dans un accident de voiture à Paris ?",
        "correctAnswer": "Lady Diana",
        "options": ["Mère Teresa", "Jacqueline Kennedy Onassis", "Lady Diana"]
    },

    {
        "date": "2025-09-01",
        "question": "Quel événement, le 1er septembre 1939, a déclenché la Seconde Guerre mondiale ?",
        "correctAnswer": "L'invasion de la Pologne par l'Allemagne nazie",
        "options": ["L'invasion de la Pologne par l'Allemagne nazie", "L'attaque de Pearl Harbor", "L'annexion de l'Autriche"]
    },
    {
        "date": "2025-09-02",
        "question": "Quel pays a signé les actes de capitulation le 2 septembre 1945, mettant fin à la Seconde Guerre mondiale ?",
        "correctAnswer": "Le Japon",
        "options": ["L'Allemagne", "L'Italie", "Le Japon"]
    },
    {
        "date": "2025-09-03",
        "question": "Quel traité, signé le 3 septembre 1783, a reconnu l'indépendance des États-Unis ?",
        "correctAnswer": "Le traité de Paris",
        "options": ["Le traité de Versailles", "Le traité de Londres", "Le traité de Paris"]
    },
    {
        "date": "2025-09-04",
        "question": "Quel inventeur a reçu un brevet pour son appareil photo à pellicule le 4 septembre 1888 ?",
        "correctAnswer": "George Eastman (Kodak)",
        "options": ["Thomas Edison", "Louis Daguerre", "George Eastman (Kodak)"]
    },
    {
        "date": "2025-09-05",
        "question": "Quel événement tragique a marqué les Jeux Olympiques de Munich le 5 septembre 1972 ?",
        "correctAnswer": "Une prise d'otages et un massacre",
        "options": ["Un boycott majeur", "Une controverse de dopage", "Une prise d'otages et un massacre"]
    },
    {
        "date": "2025-09-06",
        "question": "Quel président américain a été assassiné le 6 septembre 1901, menant Theodore Roosevelt à la présidence ?",
        "correctAnswer": "William McKinley",
        "options": ["Abraham Lincoln", "James Garfield", "William McKinley"]
    },
    {
        "date": "2025-09-07",
        "question": "Quel pays d'Amérique du Sud a déclaré son indépendance du Portugal le 7 septembre 1822 ?",
        "correctAnswer": "Le Brésil",
        "options": ["Le Brésil", "Le Mexique", "La Colombie"]
    },
    {
        "date": "2025-09-08",
        "question": "Quelle série télévisée de science-fiction a été diffusée pour la première fois le 8 septembre 1966 ?",
        "correctAnswer": "Star Trek",
        "options": ["Doctor Who", "The Twilight Zone", "Star Trek"]
    },
    {
        "date": "2025-09-09",
        "question": "Quel leader de la République Populaire de Chine, dont la mort fut annoncée le 9 septembre 1976, a marqué son histoire ?",
        "correctAnswer": "Mao Zedong",
        "options": ["Deng Xiaoping", "Zhou Enlai", "Mao Zedong"]
    },
    {
        "date": "2025-09-10",
        "question": "Que célèbre-t-on le 10 septembre, la date cible de votre compte à rebours ?",
        "correctAnswer": "Votre événement spécial !",
        "options": ["Votre anniversaire", "La journée mondiale du chocolat", "Votre événement spécial !"]
    }
];
const funStats = [
    "Saviez-vous que le Canada a plus de lacs que tous les autres pays du monde réunis ?",
    "La tour Eiffel peut être 15 cm plus haute en été qu'en hiver en raison de la dilatation thermique du fer.",
    "Le cœur d'une crevette est situé dans sa tête.",
    "Un nuage de la taille d'une baleine bleue peut contenir assez d'eau pour remplir environ 100 000 piscines olympiques.",
    "Le mot 'robot' vient du mot tchèque 'robota' qui signifie 'travail forcé'.",
    "Les éléphants sont les seuls animaux qui ne peuvent pas sauter.",
    "Les flamants roses obtiennent leur couleur rose en mangeant des crevettes et des algues bleues-vertes.",
    "Le miel ne se gâte jamais. On a trouvé du miel vieux de milliers d'années encore comestible.",
    "Les manchots sont les seuls oiseaux qui peuvent nager mais pas voler.",
    "Il y a plus de combinaisons possibles pour un jeu d'échecs que d'atomes dans l'univers connu."
];
const englishExpressions = [
    { expression: "Break a leg!", translation: "Bonne chance !" },
    { expression: "It's raining cats and dogs.", translation: "Il pleut des cordes." },
    { expression: "Bite the bullet.", translation: "Prendre sur soi (faire face à une situation difficile)." },
    { expression: "To hit the road.", translation: "Prendre la route / Partir." },
    { expression: "The ball is in your court.", translation: "C'est à toi de jouer." },
    { expression: "To spill the beans.", translation: "Vendre la mèche / Révéler un secret." },
    { expression: "Cost an arm and a leg.", translation: "Coûter les yeux de la tête (très cher)." },
    { expression: "To get cold feet.", translation: "Avoir la frousse / Avoir le trac." },
    { expression: "To speak of the devil.", translation: "Quand on parle du loup." },
    { expression: "To add insult to injury.", translation: "Ajouter l'insulte à l'injure." },
    { expression: "To hit the nail on the head.", translation: "Taper dans le mille." },
    { expression: "To bark up the wrong tree.", translation: "Faire fausse route." },
    { expression: "To feel under the weather.", translation: "Ne pas se sentir très bien / Se sentir patraque." },
    { expression: "To cut corners.", translation: "Travailler à la va-vite / Tirer au flanc." },
    { expression: "To get out of hand.", translation: "Dégénérer / Devenir incontrôlable." },
    { expression: "To make a long story short.", translation: "Pour faire court." },
    { expression: "To pull someone's leg.", translation: "Faire marcher quelqu'un / Taquiner." },
    { expression: "To wrap your head around something.", translation: "Comprendre quelque chose de complexe." },
    { expression: "To hang in there.", translation: "Tiens bon !" },
    { expression: "To lose your touch.", translation: "Perdre la main / Perdre son talent." },
    { expression: "To go back to the drawing board.", translation: "Retourner à la case départ / Repartir de zéro." },
    { expression: "To miss the boat.", translation: "Rater le coche / Manquer une opportunité." },
    { expression: "To hit the books.", translation: "Étudier assidûment / Potasser." },
    { expression: "To burn the midnight oil.", translation: "Travailler tard le soir / Veiller tard." },
    { expression: "To go the extra mile.", translation: "Faire des efforts supplémentaires." },
    { expression: "To bite off more than you can chew.", translation: "Avoir les yeux plus gros que le ventre." },
    { expression: "To hit the road.", translation: "Prendre la route / Partir." },
    { expression: "To get your act together.", translation: "Se ressaisir / Se reprendre en main." },
    { expression: "To cross that bridge when we come to it.", translation: "On avisera le moment venu." },
    { expression: "To take with a grain of salt.", translation: "Prendre avec des pincettes." },
    { expression: "To cry over spilled milk.", translation: "Pleurer sur le lait renversé (regretter quelque chose d'irréversible)." },
    { expression: "To get something off your chest.", translation: "Vider son sac." },
    { expression: "To give someone the benefit of the doubt.", translation: "Accorder le bénéfice du doute à quelqu'un." },
    { expression: "To be on the same page.", translation: "Être sur la même longueur d'onde." },
    { expression: "To beat around the bush.", translation: "Tourner autour du pot." },
    { expression: "To break the ice.", translation: "Briser la glace." },
    { expression: "To call it a day.", translation: "Arrêter pour la journée / En rester là." },
    { expression: "To get a taste of your own medicine.", translation: "Goûter à sa propre médecine / Recevoir la monnaie de sa pièce." },
    { expression: "To cut someone some slack.", translation: "Laisser un peu de répit à quelqu'un." },
    { expression: "To blow off steam.", translation: "Dégonfler sa colère / Se défouler." },
    { expression: "To be in hot water.", translation: "Être dans de beaux draps / Avoir des ennuis." },
    { expression: "To keep an eye on.", translation: "Surveiller." },
    { expression: "To keep your chin up.", translation: "Garder le moral / Garder la tête haute." },
    { expression: "To let the cat out of the bag.", translation: "Vendre la mèche / Révéler un secret (similaire à 'spill the beans')." },
    { expression: "To look on the bright side.", translation: "Voir le bon côté des choses." },
    { expression: "To pay an arm and a leg.", translation: "Payer les yeux de la tête." },
    { expression: "To pass with flying colors.", translation: "Réussir haut la main." },
    { expression: "To push your luck.", translation: "Tenter le diable / Forcer sa chance." },
    { expression: "To rub someone the wrong way.", translation: "Agacer quelqu'un / Irriter quelqu'un." },
    { expression: "To see eye to eye.", translation: "Être d'accord / Partager le même avis." },
    { expression: "To spill the beans.", translation: "Vendre la mèche / Révéler un secret." },
    { expression: "To steal someone's thunder.", translation: "Voler la vedette à quelqu'un." },
    { expression: "To take a rain check.", translation: "Remettre à plus tard / Reporter." },
    { expression: "To throw in the towel.", translation: "Jeter l'éponge." },
    { expression: "To upset the apple cart.", translation: "Mettre le bazar / Tout gâcher." },
    { expression: "Under the weather.", translation: "Malade / Pas dans son assiette." },
    { expression: "Up in the air.", translation: "En suspens / Incertain." },
    { expression: "To jump on the bandwagon.", translation: "Suivre le mouvement / S'engouffrer dans la brèche." },
    { expression: "To put all your eggs in one basket.", translation: "Mettre tous ses œufs dans le même panier." },
    { expression: "To get something out of your system.", translation: "Se libérer de quelque chose / En finir avec quelque chose." },
    { expression: "To have a chip on your shoulder.", translation: "Avoir la rancune tenace / Avoir un contentieux." },
    { expression: "To leave no stone unturned.", translation: "Ne laisser aucune pierre non retournée / Faire tout ce qui est possible." },
    { expression: "To play it by ear.", translation: "Improviser / Agir au feeling." },
    { expression: "To be a piece of cake.", translation: "Être facile comme bonjour / Être un jeu d'enfant." },
    { expression: "To cost an arm and a leg.", translation: "Coûter les yeux de la tête." },
    { expression: "To call it a night.", translation: "Arrêter pour la nuit / En rester là pour ce soir." },
    { expression: "To feel like a million dollars.", translation: "Se sentir en pleine forme / Se sentir au top." },
    { expression: "To get cold feet.", translation: "Avoir le trac / Hésiter au dernier moment." },
    { expression: "To give someone the cold shoulder.", translation: "Faire la tête à quelqu'un / Snober quelqu'un." },
    { expression: "To go down in flames.", translation: "Faire un flop retentissant / Échouer lamentablement." },
    { expression: "To have a screw loose.", translation: "Avoir une case en moins / Être un peu fou." },
    { expression: "To hit the jackpot.", translation: "Décrocher le gros lot." },
    { expression: "To keep your head above water.", translation: "Garder la tête hors de l'eau (financièrement)." },
    { expression: "To learn the ropes.", translation: "Apprendre les ficelles du métier." },
    { expression: "To be out of the woods.", translation: "Être tiré d'affaire / Être hors de danger." },
    { expression: "To pull yourself together.", translation: "Ressaisis-toi !" },
    { expression: "To ride it out.", translation: "Faire le dos rond / Subir sans broncher." },
    { expression: "To save for a rainy day.", translation: "Mettre de l'argent de côté pour les coups durs." },
    { expression: "To be sick and tired of.", translation: "En avoir marre de / En avoir ras le bol de." },
    { expression: "To put your foot in your mouth.", translation: "Mettre les pieds dans le plat." },
    { expression: "To take the bull by the horns.", translation: "Prendre le taureau par les cornes." },
    { expression: "To throw caution to the wind.", translation: "Jeter la prudence par-dessus les moulins." },
    { expression: "To make waves.", translation: "Faire des vagues (provoquer des remous)." },
    { expression: "To be up in arms.", translation: "Être furieux / Être révolté." },
    { expression: "To jump the gun.", translation: "Mettre la charrue avant les bœufs / Partir trop vite." },
    { expression: "To have a chip on one's shoulder.", translation: "Avoir la dent dure / Être susceptible." },
    { expression: "To let sleeping dogs lie.", translation: "Ne pas réveiller le chat qui dort." },
    { expression: "To be barking mad.", translation: "Être complètement fou." },
    { expression: "To catch forty winks.", translation: "Piquer un somme / Faire une sieste." },
    { expression: "To be down in the dumps.", translation: "Avoir le moral à zéro / Être déprimé." },
    { expression: "To give someone a hand.", translation: "Donner un coup de main à quelqu'un." },
    { expression: "To have a bone to pick with someone.", translation: "Avoir un os à ronger avec quelqu'un (un compte à régler)." },
    { expression: "To hit rock bottom.", translation: "Toucher le fond." },
    { expression: "To keep a straight face.", translation: "Garder son sérieux / Rester impassible." },
    { expression: "To be on thin ice.", translation: "Être sur la corde raide / Marcher sur des œufs." },
    { expression: "To be a guinea pig.", translation: "Être un cobaye." },
    { expression: "To blow your own horn.", translation: "Se vanter / Se jeter des fleurs." },
    { expression: "To come hell or high water.", translation: "Coûte que coûte / Quoi qu'il arrive." },
    { expression: "To bite the dust.", translation: "Mordre la poussière / Mourir." },
    { expression: "To be a dime a dozen.", translation: "Courir les rues / Être commun." },
    { expression: "To put your money where your mouth is.", translation: "Passer à l'acte / Joindre le geste à la parole." },
    { expression: "To get away with murder.", translation: "S'en tirer à bon compte / Rester impuni." },
    { expression: "To miss the mark.", translation: "Rater son coup / Ne pas atteindre son objectif." },
    { expression: "To be under the gun.", translation: "Être sous pression / Être au pied du mur." },
    { expression: "To go against the grain.", translation: "Aller à contre-courant / Aller à l'encontre des usages." },
    { expression: "To have your head in the clouds.", translation: "Avoir la tête dans les nuages." },
    { expression: "To keep up with the Joneses.", translation: "Faire comme tout le monde / Suivre la mode." },
    { expression: "To live and learn.", translation: "C'est en forgeant qu'on devient forgeron / On apprend de ses erreurs." },
    { expression: "To make ends meet.", translation: "Joindre les deux bouts." },
    { expression: "To put your finger on something.", translation: "Mettre le doigt sur quelque chose." },
    { expression: "To raise red flags.", translation: "Tirer la sonnette d'alarme / Alerter." },
    { expression: "To see the writing on the wall.", translation: "Voir les signes avant-coureurs." },
    { expression: "To sweeten the deal.", translation: "Édulcorer l'affaire / Rendre l'accord plus attrayant." },
    { expression: "To take a crack at something.", translation: "Essayer quelque chose / Se lancer." },
    { expression: "To run out of steam.", translation: "S'essouffler / Ne plus avoir d'énergie." },
    { expression: "To be a loose cannon.", translation: "Être un électron libre / Être imprévisible." },
    { expression: "To be caught red-handed.", translation: "Être pris la main dans le sac." },
    { expression: "To come clean.", translation: "Avouer / Tout révéler." },
    { expression: "To be dead serious.", translation: "Être très sérieux." },
    { expression: "To draw a blank.", translation: "Avoir un trou de mémoire / Ne rien trouver." },
    { expression: "To get a handle on something.", translation: "Maîtriser quelque chose / Comprendre." },
    { expression: "To have a big mouth.", translation: "Avoir la langue bien pendue / Ne pas savoir garder un secret." },
    { expression: "To keep an open mind.", translation: "Garder l'esprit ouvert." },
    { expression: "To let bygones be bygones.", translation: "Tourner la page / Oublier le passé." },
    { expression: "To make a mountain out of a molehill.", translation: "Faire toute une montagne d'une taupinière." },
    { expression: "To pass the buck.", translation: "Renvoyer la balle / Se défausser." },
    { expression: "To read between the lines.", translation: "Lire entre les lignes." },
    { expression: "To hit the ground running.", translation: "Démarrer sur les chapeaux de roue." },
    { expression: "To roll with the punches.", translation: "S'adapter aux coups / Faire face aux difficultés." },
    { expression: "To be the bee's knees.", translation: "Être la crème de la crème / Être exceptionnel." },
    { expression: "To hit the road.", translation: "Prendre la route / Partir." },
    { expression: "To stand your ground.", translation: "Tenir bon / Ne pas céder." },
    { expression: "To take a leap of faith.", translation: "Faire un acte de foi / Se jeter à l'eau." },
    { expression: "To be on cloud nine.", translation: "Être au septième ciel." },
    { expression: "To have a gut feeling.", translation: "Avoir une intuition / Le pressentiment." },
    { expression: "To put your best foot forward.", translation: "Faire de son mieux / Donner le meilleur de soi-même." },
    { expression: "To throw a wrench in the works.", translation: "Jeter une clé dans les rouages / Mettre des bâtons dans les roues." },
    { expression: "To be all ears.", translation: "Être tout ouïe." },
    { expression: "To be caught between a rock and a hard place.", translation: "Être pris entre l'arbre et l'écorce / Être entre le marteau et l'enclume." },
    { expression: "To clear the air.", translation: "Remettre les pendules à l'heure / Disperser les tensions." },
    { expression: "To be down to earth.", translation: "Avoir les pieds sur terre." },
    { expression: "To bite the hand that feeds you.", translation: "Mordre la main qui vous nourrit." },
    { expression: "To come to a head.", translation: "Arriver à un point critique / Atteindre son paroxysme." },
    { expression: "To face the music.", translation: "Faire face aux conséquences / Assumer ses responsabilités." },
    { expression: "To get your ducks in a row.", translation: "Mettre de l'ordre / Organiser les choses." },
    { expression: "To have a one-track mind.", translation: "Avoir une idée fixe." },
    { expression: "To keep a low profile.", translation: "Faire profil bas." },
    { expression: "To let someone off the hook.", translation: "Laisser quelqu'un tranquille / Dégager quelqu'un d'une situation." },
    { expression: "To lose your marbles.", translation: "Perdre la tête / Devenir fou." },
    { expression: "To make hay while the sun shines.", translation: "Battre le fer tant qu'il est chaud." },
    { expression: "To pick up the pieces.", translation: "Ramasser les morceaux / Reconstruire." },
    { expression: "To pull strings.", translation: "Tirer les ficelles / User de son influence." },
    { expression: "To put your money where your mouth is.", translation: "Joindre le geste à la parole / Tenir ses promesses." },
    { expression: "To rack your brain.", translation: "Se creuser la tête / Se casser la tête." },
    { expression: "To save face.", translation: "Sauver la face." },
    { expression: "To smell a rat.", translation: "Sentir l'arnaque / Se douter de quelque chose." },
    { expression: "To split hairs.", translation: "Couper les cheveux en quatre." },
    { expression: "To take the plunge.", translation: "Franchir le pas / Se jeter à l'eau." },
    { expression: "To wear your heart on your sleeve.", translation: "Avoir le cœur sur la main / Ne pas cacher ses émotions." },
    { expression: "To have egg on your face.", translation: "Avoir l'air ridicule / Être embarrassé." },
    { expression: "To go with the flow.", translation: "Suivre le courant / Se laisser porter." },
    { expression: "To be in the same boat.", translation: "Être dans le même bateau." },
    { expression: "To get your second wind.", translation: "Reprendre son souffle / Retrouver de l'énergie." },
    { expression: "To have a field day.", translation: "S'en donner à cœur joie / S'éclater." },
    { expression: "To make ends meet.", translation: "Joindre les deux bouts." },
    { expression: "To be back to square one.", translation: "Retourner à la case départ." },
    { expression: "To be on the fence.", translation: "Hésiter / Être indécis." },
    { expression: "To cry wolf.", translation: "Crier au loup (alarme inutile)." },
    { expression: "To go from strength to strength.", translation: "Aller de mieux en mieux / Progresser constamment." },
    { expression: "To have a short fuse.", translation: "S'énerver facilement / Avoir la mèche courte." },
    { expression: "To keep your shirt on.", translation: "Garder son calme / Ne pas s'énerver." },
    { expression: "To let off steam.", translation: "Se défouler / Évacuer le stress." },
    { expression: "To nail it.", translation: "Réussir parfaitement / Gérer." },
    { expression: "To play hardball.", translation: "Jouer les durs / Être inflexible." },
    { expression: "To be wet behind the ears.", translation: "Être novice / Être inexpérimenté." },
    { expression: "To put a damper on something.", translation: "Gâcher quelque chose / Jeter un froid." },
    { expression: "To rule the roost.", translation: "Mener la danse / Faire la loi." },
    { expression: "To sell like hot cakes.", translation: "Se vendre comme des petits pains." },
    { expression: "To pull yourself up by your bootstraps.", translation: "Se prendre en main / S'en sortir par soi-même." },
    { expression: "To take a turn for the worse.", translation: "Prendre une mauvaise tournure." },
    { expression: "To walk on eggshells.", translation: "Marcher sur des œufs / Être très prudent." },
    { expression: "To be worth your salt.", translation: "Valoir son pesant d'or / Être compétent." },
    { expression: "To blow smoke.", translation: "Raconter des salades / Flatter sans sincérité." },
    { expression: "To come full circle.", translation: "La boucle est bouclée / Revenir au point de départ." },
    { expression: "To grease someone's palm.", translation: "Graisser la patte à quelqu'un / Soudoyer." },
    { expression: "To have a knack for something.", translation: "Avoir le don de / Être doué pour." },
    { expression: "To lose your temper.", translation: "Perdre son calme / S'énerver." },
    { expression: "To make a killing.", translation: "Faire fortune / Faire un tabac." },
    { expression: "To put your money where your mouth is.", translation: "Joindre le geste à la parole / Tenir ses promesses." },
    { expression: "To ring a bell.", translation: "Dire quelque chose / Rappeler quelque chose (faire penser à)." },
    { expression: "To sleep on it.", translation: "Dormir dessus (réfléchir avant de décider)." },
    { expression: "To stick to your guns.", translation: "Tenir bon / Ne pas changer d'avis." },
    { expression: "To take the high road.", translation: "Adopter une attitude noble / Choisir la bonne voie." },
    { expression: "To be in over your head.", translation: "Être dépassé / Avoir la tête sous l'eau." },
    { expression: "To hit the ceiling.", translation: "Piquer une crise / Voir rouge." },
    { expression: "To live on borrowed time.", translation: "Vivre du temps emprunté / Survie inattendue." },
    { expression: "To make light of something.", translation: "Prendre quelque chose à la légère." },
    { expression: "To pull a fast one.", translation: "Faire un coup bas / Tromper quelqu'un." },
    { expression: "To put the cart before the horse.", translation: "Mettre la charrue avant les bœufs." },
    { expression: "To play it safe.", translation: "Jouer la carte de la sécurité / Ne pas prendre de risques." },
    { expression: "To cut to the chase.", translation: "Aller droit au but." },
    { expression: "To be a cold fish.", translation: "Être froid / Être distant." },
    { expression: "To bite the bullet.", translation: "Faire contre mauvaise fortune bon cœur / Affronter la difficulté." },
    { expression: "To have a way with words.", translation: "Avoir la tchatche / Avoir le don des mots." },
    { expression: "To get your head in the game.", translation: "Se concentrer / Être attentif." },
    { expression: "To be on the ball.", translation: "Être au taquet / Être à l'affût." },
    { expression: "To hit a wall.", translation: "Atteindre un mur / Ne plus progresser." },
    { expression: "To keep your wits about you.", translation: "Garder son sang-froid / Être lucide." },
    { expression: "To make a mountain out of a molehill.", translation: "En faire tout un fromage / Faire une montagne d'une taupinière." },
    { expression: "To pull out all the stops.", translation: "Mettre le paquet / Ne reculer devant rien." },
    { expression: "To put your thinking cap on.", translation: "Se creuser les méninges / Réfléchir." },
    { expression: "To run like clockwork.", translation: "Marcher comme une horloge / Fonctionner parfaitement." },
    { expression: "To see eye to eye.", translation: "Être d'accord / Avoir le même point de vue." },
    { expression: "To turn a blind eye.", translation: "Fermer les yeux (sur quelque chose)." },
    { expression: "To be a big shot.", translation: "Être un gros bonnet / Être quelqu'un d'important." },
    { expression: "To have a loose tongue.", translation: "Avoir la langue bien pendue / Ne pas tenir sa langue." },
    { expression: "To get a foot in the door.", translation: "Mettre le pied à l'étrier / Faire ses débuts." },
    { expression: "To be a copycat.", translation: "Être un imitateur / Un copieur." },
    { expression: "To spill blood.", translation: "Verser le sang." },
    { expression: "To hit the spot.", translation: "Tomber à pic / Faire du bien (nourriture, boisson)." },
    { expression: "To jump through hoops.", translation: "Faire des pieds et des mains / Faire des pirouettes." },
    { expression: "To keep a stiff upper lip.", translation: "Garder son sang-froid / Ne pas montrer ses émotions." },
    { expression: "To lead someone on.", translation: "Faire des fausses promesses / Donner de faux espoirs." },
    { expression: "To live on the edge.", translation: "Vivre dangereusement / Vivre à fond." },
    { expression: "To make a fresh start.", translation: "Prendre un nouveau départ." },
    { expression: "To paddle your own canoe.", translation: "Se débrouiller seul / Ne compter sur personne." },
    { expression: "To pay your dues.", translation: "Payer ses dettes / Faire ses preuves." },
    { expression: "To put your best foot forward.", translation: "Faire de son mieux / Se présenter sous son meilleur jour." },
    { expression: "To rain on someone's parade.", translation: "Gâcher la fête de quelqu'un / Doucher l'enthousiasme." },
    { expression: "To run a tight ship.", translation: "Mener sa barque de main de maître / Gérer rigoureusement." },
    { expression: "To spill the tea.", translation: "Raconter les potins / Partager les ragots." },
    { expression: "To stand by someone.", translation: "Soutenir quelqu'un." },
    { expression: "To take a backseat.", translation: "Passer au second plan / S'effacer." },
    { expression: "To walk on air.", translation: "Flotter sur un nuage / Être aux anges." },
    { expression: "To be out of line.", translation: "Dépasser les bornes / Franchir les limites." },
    { expression: "To bite the dust.", translation: "Mordre la poussière / Échouer lamentablement." },
    { expression: "To come out of the woodwork.", translation: "Sortir de nulle part / Apparaître soudainement." },
    { expression: "To face the music.", translation: "Faire face aux conséquences." },
    { expression: "To get a raw deal.", translation: "Être mal traité / Subir une injustice." },
    { expression: "To have a foot in both camps.", translation: "Avoir un pied dans deux camps / Jouer sur deux tableaux." },
    { expression: "To keep your ear to the ground.", translation: "Être à l'écoute / Se tenir informé." },
    { expression: "To let the chips fall where they may.", translation: "Laisser les choses suivre leur cours / Advienne que pourra." },
    { expression: "To make a killing.", translation: "Faire fortune." },
    { expression: "To pick up the tab.", translation: "Régler l'addition / Payer la note." },
    { expression: "To play second fiddle.", translation: "Jouer les seconds rôles / Être en position subalterne." },
    { expression: "To put your foot down.", translation: "Taper du poing sur la table / S'imposer." },
    { expression: "To rain cats and dogs.", translation: "Pleuvoir des cordes." },
    { expression: "To rub salt in the wound.", translation: "Remuer le couteau dans la plaie." },
    { expression: "To shake a leg.", translation: "Se dépêcher / Se remuer." },
    { expression: "To have ants in your pants.", translation: "Avoir la bougeotte / Ne pas tenir en place." },
    { expression: "To be all thumbs.", translation: "Être maladroit / Avoir deux mains gauches." },
    { expression: "To bite off more than one can chew.", translation: "Avoir les yeux plus gros que le ventre." },
    { expression: "To cut the mustard.", translation: "Faire l'affaire / Être à la hauteur." },
    { expression: "To be in seventh heaven.", translation: "Être au septième ciel." },
    { expression: "To give someone the benefit of the doubt.", translation: "Accorder le bénéfice du doute." },
    { expression: "To have a heart of gold.", translation: "Avoir un cœur d'or." },
    { expression: "To keep a low profile.", translation: "Faire profil bas." },
    { expression: "To let sleeping dogs lie.", translation: "Ne pas réveiller le chat qui dort." },
    { expression: "To put all your eggs in one basket.", translation: "Mettre tous ses œufs dans le même panier." },
    { expression: "To run out of gas.", translation: "Tomber en panne d'énergie / S'essouffler." },
    { expression: "To sleep like a log.", translation: "Dormir comme une bûche." },
    { expression: "To steal the show.", translation: "Voler la vedette." },
    { expression: "To take a back seat.", translation: "Passer au second plan." },
    { expression: "To burn the candle at both ends.", translation: "Brûler la chandelle par les deux bouts." },
    { expression: "To jump for joy.", translation: "Sauter de joie." },
    { expression: "To keep your chin up.", translation: "Garder la tête haute." },
    { expression: "To leave no stone unturned.", translation: "Ne laisser aucune pierre non retournée." },
    { expression: "To pull someone's leg.", translation: "Faire marcher quelqu'un." },
    { expression: "To put your best foot forward.", translation: "Faire de son mieux." },
    { expression: "To shake a leg.", translation: "Se dépêcher." },
    { expression: "To take a rain check.", translation: "Remettre à plus tard." },
    { expression: "To twist someone's arm.", translation: "Forcer la main à quelqu'un." },
    { expression: "To be in your element.", translation: "Être dans son élément." },
    { expression: "To bite off more than you can chew.", translation: "Avoir les yeux plus gros que le ventre." },
    { expression: "To get a second wind.", translation: "Reprendre son souffle." },
    { expression: "To have a short fuse.", translation: "Avoir la mèche courte." },
    { expression: "To hit the sack.", translation: "Aller se coucher / Dormir." },
    { expression: "To put your foot in your mouth.", translation: "Mettre les pieds dans le plat." },
    { expression: "To be a straight shooter.", translation: "Être direct / Franc." },
    { expression: "To chew the fat.", translation: "Discuter / Bavarder." },
    { expression: "To get cold feet.", translation: "Avoir le trac." },
    { expression: "To hit the road.", translation: "Prendre la route." },
    { expression: "To keep a low profile.", translation: "Faire profil bas." },
    { expression: "To make waves.", translation: "Faire des vagues." },
    { expression: "To pull yourself together.", translation: "Ressaisis-toi." },
    { expression: "To be a tough nut to crack.", translation: "Être une personne difficile à cerner / Un problème coriace." },
    { expression: "To clean up your act.", translation: "Se reprendre en main / Améliorer sa conduite." },
    { expression: "To have a frog in your throat.", translation: "Avoir un chat dans la gorge." },
    { expression: "To keep your chin up.", translation: "Garder la tête haute." },
    { expression: "To leave no stone unturned.", translation: "Ne laisser aucune pierre non retournée." },
    { expression: "To make ends meet.", translation: "Joindre les deux bouts." },
    { expression: "To pick up the tab.", translation: "Payer l'addition." },
    { expression: "To play it by ear.", translation: "Improviser." },
    { expression: "To put someone on the spot.", translation: "Mettre quelqu'un dans l'embarras." },
    { expression: "To read between the lines.", translation: "Lire entre les lignes." },
    { expression: "To take a leap of faith.", translation: "Faire un acte de foi." },
    { expression: "To throw in the towel.", translation: "Jeter l'éponge." },
    { expression: "To be on thin ice.", translation: "Être sur la corde raide." },
    { expression: "To get off on the wrong foot.", translation: "Commencer du mauvais pied." },
    { expression: "To have a loose tongue.", translation: "Avoir la langue bien pendue." },
    { expression: "To keep an eye on.", translation: "Surveiller." },
    { expression: "To let sleeping dogs lie.", translation: "Ne pas réveiller le chat qui dort." },
    { expression: "To lose your touch.", translation: "Perdre la main." },
    { expression: "To make a long story short.", translation: "Pour faire court." },
    { expression: "To pass the buck.", translation: "Renvoyer la balle." },
    { expression: "To play devil's advocate.", translation: "Se faire l'avocat du diable." },
    { expression: "To put your foot down.", translation: "S'imposer / Taper du poing sur la table." },
    { expression: "To run out of steam.", translation: "S'essouffler." },
    { expression: "To take a rain check.", translation: "Remettre à plus tard." },
    { expression: "To upset the apple cart.", translation: "Mettre le bazar." },
    { expression: "To bite the hand that feeds you.", translation: "Mordre la main qui vous nourrit." },
    { expression: "To come hell or high water.", translation: "Coûte que coûte." },
    { expression: "To go with the flow.", translation: "Suivre le courant." },
    { expression: "To have a chip on your shoulder.", translation: "Avoir une rancune." },
    { expression: "To hit rock bottom.", translation: "Toucher le fond." },
    { expression: "To keep your wits about you.", translation: "Garder son sang-froid." },
    { expression: "To let someone off the hook.", translation: "Laisser quelqu'un tranquille." },
    { expression: "To pull a fast one.", translation: "Faire un coup bas." },
    { expression: "To put all your eggs in one basket.", translation: "Mettre tous ses œufs dans le même panier." },
    { expression: "To save face.", translation: "Sauver la face." },
    { expression: "To see eye to eye.", translation: "Être d'accord." },
    { expression: "To sweeten the deal.", translation: "Rendre l'accord plus attrayant." },
    { expression: "To throw caution to the wind.", translation: "Jeter la prudence par-dessus les moulins." },
    { expression: "To walk on eggshells.", translation: "Marcher sur des œufs." },
    { expression: "To be all ears.", translation: "Être tout ouïe." },
    { expression: "To break the ice.", translation: "Briser la glace." },
    { expression: "To cry over spilled milk.", translation: "Pleurer sur le lait renversé." },
    { expression: "To feel under the weather.", translation: "Ne pas se sentir bien." },
    { expression: "To get something off your chest.", translation: "Vider son sac." },
    { expression: "To hang in there.", translation: "Tiens bon !" },
    { expression: "To learn the ropes.", translation: "Apprendre les ficelles du métier." },
    { expression: "To look on the bright side.", translation: "Voir le bon côté des choses." },
    { expression: "To pull yourself up by your bootstraps.", translation: "S'en sortir par soi-même." },
    { expression: "To run a tight ship.", translation: "Gérer rigoureusement." },
    { expression: "To speak of the devil.", translation: "Quand on parle du loup." },
    { expression: "To stick to your guns.", translation: "Tenir bon (sur ses opinions)." },
    { expression: "To be in deep water.", translation: "Être dans de beaux draps / En difficulté." },
    { expression: "To cut corners.", translation: "Travailler à la va-vite." },
    { expression: "To give someone the cold shoulder.", translation: "Snober quelqu'un." },
    { expression: "To hit the books.", translation: "Potasser / Étudier." },
    { expression: "To keep an open mind.", translation: "Garder l'esprit ouvert." },
    { expression: "To make a comeback.", translation: "Faire un retour." },
    { expression: "To pay an arm and a leg.", translation: "Payer les yeux de la tête." },
    { expression: "To pull strings.", translation: "Tirer les ficelles." },
    { expression: "To put your best foot forward.", translation: "Faire de son mieux." },
    { expression: "To rub someone the wrong way.", translation: "Agacer quelqu'un." },
    { expression: "To sleep on it.", translation: "Dormir dessus." },
    { expression: "To steal someone's thunder.", translation: "Voler la vedette." },
    { expression: "To take a backseat.", translation: "Passer au second plan." },
    { expression: "To throw a wrench in the works.", translation: "Mettre des bâtons dans les roues." },
    { expression: "To be on cloud nine.", translation: "Être au septième ciel." },
    { expression: "To jump the gun.", translation: "Mettre la charrue avant les bœufs." },
    { expression: "To play hardball.", translation: "Jouer les durs." },
    { expression: "To be a big fish in a small pond.", translation: "Être un gros poisson dans une petite mare." },
    { expression: "To bite the bullet.", translation: "Faire contre mauvaise fortune bon cœur." },
    { expression: "To get something off your chest.", translation: "Vider son sac." },
    { expression: "To have a sweet tooth.", translation: "Être gourmand." },
    { expression: "To hit the road.", translation: "Prendre la route." },
    { expression: "To keep someone in the loop.", translation: "Tenir quelqu'un informé." },
    { expression: "To let sleeping dogs lie.", translation: "Ne pas réveiller le chat qui dort." },
    { expression: "To put all your eggs in one basket.", translation: "Mettre tous ses œufs dans le même panier." },
    { expression: "To spill the beans.", translation: "Vendre la mèche." },
    { expression: "To take a rain check.", translation: "Remettre à plus tard." },
    { expression: "To be up in arms.", translation: "Être furieux." },
    { expression: "To cross that bridge when you come to it.", translation: "On avisera le moment venu." },
    { expression: "To get something out of your system.", translation: "Se libérer de quelque chose." },
    { expression: "To have a field day.", translation: "S'en donner à cœur joie." },
    { expression: "To make a killing.", translation: "Faire fortune." },
    { expression: "To put your foot in your mouth.", translation: "Mettre les pieds dans le plat." },
    { expression: "To read between the lines.", translation: "Lire entre les lignes." },
    { expression: "To save for a rainy day.", translation: "Mettre de l'argent de côté." },
    { expression: "To throw in the towel.", translation: "Jeter l'éponge." },
    { expression: "To walk on air.", translation: "Flotter sur un nuage." },
    { expression: "To be on the fence.", translation: "Hésiter." },
    { expression: "To make ends meet.", translation: "Joindre les deux bouts." },
    { expression: "To play it safe.", translation: "Jouer la sécurité." },
    { expression: "To pull yourself together.", translation: "Ressaisis-toi." },
    { expression: "To run like clockwork.", translation: "Marcher comme une horloge." },
    { expression: "To take the bull by the horns.", translation: "Prendre le taureau par les cornes." },
    { expression: "To wear your heart on your sleeve.", translation: "Avoir le cœur sur la main." },
    { expression: "To be in hot water.", translation: "Être dans de beaux draps." },
    { expression: "To keep your head above water.", translation: "Garder la tête hors de l'eau." },
    { expression: "To be sick and tired of.", translation: "En avoir marre de." },
    { expression: "To go the extra mile.", translation: "Faire des efforts supplémentaires." },
    { expression: "To have a big mouth.", translation: "Avoir la langue bien pendue." },
    { expression: "To hit the jackpot.", translation: "Décrocher le gros lot." },
    { expression: "To jump on the bandwagon.", translation: "Suivre le mouvement." },
    { expression: "To learn the ropes.", translation: "Apprendre les ficelles du métier." },
    { expression: "To lose your marbles.", translation: "Perdre la tête." },
    { expression: "To make hay while the sun shines.", translation: "Battre le fer tant qu'il est chaud." },
    { expression: "To pass with flying colors.", translation: "Réussir haut la main." },
    { expression: "To push your luck.", translation: "Tenter le diable." },
    { expression: "To see the writing on the wall.", translation: "Voir les signes avant-coureurs." },
    { expression: "To throw a wrench in the works.", translation: "Mettre des bâtons dans les roues." },
    { expression: "To be out of the woods.", translation: "Être tiré d'affaire." },
    { expression: "To bite the dust.", translation: "Mordre la poussière." },
    { expression: "To come clean.", translation: "Avouer." },
    { expression: "To draw a blank.", translation: "Avoir un trou de mémoire." },
    { expression: "To get a handle on something.", translation: "Maîtriser quelque chose." },
    { expression: "To have a knack for something.", translation: "Avoir le don de." },
    { expression: "To keep your shirt on.", translation: "Garder son calme." },
    { expression: "To let off steam.", translation: "Se défouler." },
    { expression: "To play second fiddle.", translation: "Jouer les seconds rôles." },
    { expression: "To put your best foot forward.", translation: "Faire de son mieux." },
    { expression: "To go back to the drawing board.", translation: "Retourner à la case départ." },
    { expression: "To miss the boat.", translation: "Rater le coche." },
    { expression: "To put your money where your mouth is.", translation: "Passer à l'acte." },
    { expression: "To run out of steam.", translation: "S'essouffler." },
    { expression: "To be a cold fish.", translation: "Être froid." },
    { expression: "To hit the ceiling.", translation: "Piquer une crise." },
    { expression: "To live on borrowed time.", translation: "Vivre du temps emprunté." },
    { expression: "To make light of something.", translation: "Prendre à la légère." },
    { expression: "To pull a fast one.", translation: "Faire un coup bas." },
    { expression: "To put the cart before the horse.", translation: "Mettre la charrue avant les bœufs." },
    { expression: "To take the high road.", translation: "Adopter une attitude noble." },
    { expression: "To turn a blind eye.", translation: "Fermer les yeux (sur quelque chose)." },
    { expression: "To be worth your salt.", translation: "Valoir son pesant d'or." },
    { expression: "To blow smoke.", translation: "Raconter des salades." },
    { expression: "To come full circle.", translation: "La boucle est bouclée." },
    { expression: "To grease someone's palm.", translation: "Graisser la patte à quelqu'un." },
    { expression: "To lose your temper.", translation: "Perdre son calme." },
    { expression: "To make a killing.", translation: "Faire fortune." },
    { expression: "To ring a bell.", translation: "Rappeler quelque chose." },
    { expression: "To save face.", translation: "Sauver la face." },
    { expression: "To smell a rat.", translation: "Sentir l'arnaque." },
    { expression: "To split hairs.", translation: "Couper les cheveux en quatre." },
    { expression: "To take the plunge.", translation: "Franchir le pas." },
    { expression: "To wear your heart on your sleeve.", translation: "Avoir le cœur sur la main." },
    { expression: "To be in over your head.", translation: "Être dépassé." },
    { expression: "To make waves.", translation: "Faire des vagues." },
    { expression: "To put your thinking cap on.", translation: "Se creuser les méninges." },
    { expression: "To see the writing on the wall.", translation: "Voir les signes avant-coureurs." },
    { expression: "To be a sitting duck.", translation: "Être une cible facile." },
    { expression: "To bite the bullet.", translation: "Prendre sur soi." },
    { expression: "To call it a day.", translation: "Arrêter pour la journée." },
    { expression: "To feel like a million dollars.", translation: "Se sentir en pleine forme." },
    { expression: "To get your act together.", translation: "Se ressaisir." },
    { expression: "To have a gut feeling.", translation: "Avoir une intuition." },
    { expression: "To keep a stiff upper lip.", translation: "Garder son sang-froid." },
    { expression: "To make a mountain out of a molehill.", translation: "Faire toute une montagne d'une taupinière." },
    { expression: "To pass with flying colors.", translation: "Réussir haut la main." },
    { expression: "To pull strings.", translation: "Tirer les ficelles." },
    { expression: "To read between the lines.", translation: "Lire entre les lignes." },
    { expression: "To save for a rainy day.", translation: "Mettre de l'argent de côté." },
    { expression: "To take a crack at something.", translation: "Essayer quelque chose." },
    { expression: "To throw in the towel.", translation: "Jeter l'éponge." },
    { expression: "To be up in the air.", translation: "En suspens." },
    { expression: "To jump for joy.", translation: "Sauter de joie." },
    { expression: "To play it by ear.", translation: "Improviser." },
    { expression: "To be all thumbs.", translation: "Être maladroit." },
    { expression: "To catch forty winks.", translation: "Piquer un somme." },
    { expression: "To be down in the dumps.", translation: "Avoir le moral à zéro." },
    { expression: "To give someone a hand.", translation: "Donner un coup de main." },
    { expression: "To have a bone to pick with someone.", translation: "Avoir un compte à régler." },
    { expression: "To hit the ground running.", translation: "Démarrer sur les chapeaux de roue." },
    { expression: "To keep your chin up.", translation: "Garder la tête haute." },
    { expression: "To let bygones be bygones.", translation: "Tourner la page." },
    { expression: "To roll with the punches.", translation: "S'adapter aux coups." },
    { expression: "To be the bee's knees.", translation: "Être la crème de la crème." },
    { expression: "To take the bull by the horns.", translation: "Prendre le taureau par les cornes." },
    { expression: "To throw caution to the wind.", translation: "Jeter la prudence par-dessus les moulins." },
    { expression: "To be in the same boat.", translation: "Être dans le même bateau." },
    { expression: "To put all your eggs in one basket.", translation: "Mettre tous ses œufs dans le même panier." },
    { expression: "To be wet behind the ears.", translation: "Être novice." },
    { expression: "To clean up your act.", translation: "Se reprendre en main." },
    { expression: "To have a frog in your throat.", translation: "Avoir un chat dans la gorge." },
    { expression: "To hit a wall.", translation: "Atteindre un mur." },
    { expression: "To live on the edge.", translation: "Vivre dangereusement." },
    { expression: "To make a fresh start.", translation: "Prendre un nouveau départ." },
    { expression: "To play hardball.", translation: "Jouer les durs." },
    { expression: "To run like clockwork.", translation: "Marcher comme une horloge." },
    { expression: "To be caught red-handed.", translation: "Être pris la main dans le sac." },
    { expression: "To have egg on your face.", translation: "Avoir l'air ridicule." },
    { expression: "To pull yourself up by your bootstraps.", translation: "S'en sortir par soi-même." },
    { expression: "To stand your ground.", translation: "Tenir bon." },
    { expression: "To take a leap of faith.", translation: "Faire un acte de foi." },
    { expression: "To walk on eggshells.", translation: "Marcher sur des œufs." },
    { expression: "To blow your own horn.", translation: "Se vanter." },
    { expression: "To come to a head.", translation: "Arriver à un point critique." },
    { expression: "To face the music.", translation: "Faire face aux conséquences." },
    { expression: "To get a raw deal.", translation: "Être mal traité." },
    { expression: "To keep your ear to the ground.", translation: "Être à l'écoute." },
    { expression: "To lose your shirt.", translation: "Tout perdre." },
    { expression: "To make hay while the sun shines.", translation: "Battre le fer tant qu'il est chaud." },
    { expression: "To pull out all the stops.", translation: "Mettre le paquet." },
    { expression: "To see the writing on the wall.", translation: "Voir les signes avant-coureurs." },
    { expression: "To put your best foot forward.", translation: "Faire de son mieux." },
    { expression: "To call it a night.", translation: "Arrêter pour la nuit." },
    { expression: "To be a tough nut to crack.", translation: "Être un problème coriace." },
    { expression: "To put a damper on something.", translation: "Gâcher quelque chose." },
    { expression: "To throw a curveball.", translation: "Lancer une balle courbe / Surprendre." },
    { expression: "To be on the same page.", translation: "Être sur la même longueur d'onde." },
    { expression: "To beat around the bush.", translation: "Tourner autour du pot." },
    { expression: "To jump on the bandwagon.", translation: "Suivre le mouvement." },
    { expression: "To put all your eggs in one basket.", translation: "Mettre tous ses œufs dans le même panier." },
    { expression: "To bite off more than you can chew.", translation: "Avoir les yeux plus gros que le ventre." },
    { expression: "To jump for joy.", translation: "Sauter de joie." },
    { expression: "To be a copycat.", translation: "Être un copieur." },
    { expression: "To bite the dust.", translation: "Mordre la poussière." },
    { expression: "To be in hot water.", translation: "Être dans de beaux draps." },
    { expression: "To keep your chin up.", translation: "Garder la tête haute." },
    { expression: "To leave no stone unturned.", translation: "Ne laisser aucune pierre non retournée." },
    { expression: "To pick up the tab.", translation: "Payer l'addition." },
    { expression: "To play it by ear.", translation: "Improviser." },
    { expression: "To put someone on the spot.", translation: "Mettre quelqu'un dans l'embarras." },
    { expression: "To run out of steam.", translation: "S'essouffler." },
    { expression: "To take a rain check.", translation: "Remettre à plus tard." },
    { expression: "To walk on air.", translation: "Flotter sur un nuage." },
    { expression: "To be on thin ice.", translation: "Être sur la corde raide." },
    { expression: "To cut corners.", translation: "Travailler à la va-vite." },
    { expression: "To give someone the cold shoulder.", translation: "Snober quelqu'un." },
    { expression: "To hit the books.", translation: "Potasser." },
    { expression: "To keep an open mind.", translation: "Garder l'esprit ouvert." },
    { expression: "To make a comeback.", translation: "Faire un retour." },
    { expression: "To pay an arm and a leg.", translation: "Payer les yeux de la tête." },
    { expression: "To pull strings.", translation: "Tirer les ficelles." },
    { expression: "To rub someone the wrong way.", translation: "Agacer quelqu'un." },
    { expression: "To sleep on it.", translation: "Dormir dessus." },
    { expression: "To take a backseat.", translation: "Passer au second plan." },
    { expression: "To throw a wrench in the works.", translation: "Mettre des bâtons dans les roues." },
    { expression: "To be all ears.", translation: "Être tout ouïe." },
    { expression: "To break the ice.", translation: "Briser la glace." },
    { expression: "To cry over spilled milk.", translation: "Pleurer sur le lait renversé." },
    { expression: "To get something off your chest.", translation: "Vider son sac." },
    { expression: "To hang in there.", translation: "Tiens bon !" },
    { expression: "To learn the ropes.", translation: "Apprendre les ficelles du métier." },
    { expression: "To look on the bright side.", translation: "Voir le bon côté des choses." },
    { expression: "To pull yourself up by your bootstraps.", translation: "S'en sortir par soi-même." },
    { expression: "To run a tight ship.", translation: "Gérer rigoureusement." },
    { expression: "To speak of the devil.", translation: "Quand on parle du loup." },
    { expression: "To stick to your guns.", translation: "Tenir bon (sur ses opinions)." }
];